USE ROLE ACCOUNTADMIN;


SELECT CURRENT_REGION();

CREATE ACCOUNT DECONNECT_HOL_DEMO
ADMIN_NAME = 'KrishKabi'
ADMIN_PASSWORD = 'Temppassword123'
MUST_CHANGE_PASSWORD = TRUE
EMAIL = 'krish.kabi@wppmedia.com'
EDITION = enterprise
REGION = aws_us_west_2
POLARIS = TRUE;